### ISSUE TITLE
Any possibility of implementing navigation?

### ISSUE THREAD

**Issue by rkiyanchuk** [flyandi/mazda-enhanced-compass#3]
Your Mazda compass project looks very promising.

Since you've already got some experience with this, do you think there are any chances to get navigation working on the Infotainment system?

Thanks!

**Comment by flyandi** [comment]
Not without internet connection. Writing a custom router would be too much. 
It has WiFi but in my testing it is very unstable and almost not usable. Probably that's the main reason why they disabled it by default. Somebody at jci needs to compile a stable driver.
On Nov 30, 2015 9:33 PM, Ruslan Kiianchuk notifications@github.com wrote:Your Mazda compass project looks very promising.

Since you've already got some experience with this, do you think there are any chances to get navigation working on the Infotainment system?

Thanks!

**Comment by rkiyanchuk** [comment]
I see. I've also tried WiFi and it wasn't reliable for me as well. But I think it might be possible to get stable connection by using portable hotspot and plugging it into USB, so that in-built WiFi isn't needed.

On the other hand I don't understand why automakers started putting big displays into the cars, but didn't think to simply integrate it with the smartphone that everyone has now and just use its Internet connection, navigation etc. Even simple screen mirroring would do the job.

Anyway, thanks for the reply!
